README.md, terraform/terraform.tfvars.example
Main changes:
- remove step about `terraform plan`, as `terraform apply` shows the plan and prompts you to go forward with it (tested)
- remove the `environment` entry from the variable file, so that it needs to be passed via CLI - this relates to this PR https://github.com/alphagov/re-build-systems-config/pull/4
- general clean up
=> Improve documentation and force passing environment name from CLI

terraform/main.tf, terraform/vpc.tf
Update version of terraform-aws-modules/vpc/aws to current version. Terraform tested and Jenkins starts up no probs
Solo: @poveyd
=> Update version of vpc module

docker/Dockerfile
For consistency, I change the destination path to `/usr/share/jenkins/ref/`
as we copy all the configuration files to there.
I have tested this and the logs are still flowing.
The [/usr/local/bin/jenkins.sh](https://github.com/jenkinsci/docker/blob/master/jenkins.sh) script (which launches Jenkins) copies all the files
from `/usr/share/jenkins/ref/` to the Jenkins home folder before invoking `java`
with the option `-Djava.util.logging.config.file=/var/jenkins_home/log.properties"`,
so by then the `log.properties` should be already in its final location.
=> Change destination path for log.properties in Dockerfile

terraform/cloud-init/master-xenial-16.04-amd64-server.yaml, terraform/instances.tf, terraform/variables.tf
There is a need for persistent storage by the master to keep the job history and jenkins specific configuration.
This PR creates a persistent EBS volume that gets attached to the master instance and does not get destroyed between instance re-spins.
The partitioning, formatting and mounting of the EBS volume cannot be managed by cloud-init, because a race condition exists when the instance is created and where cloud-init starts and completes, before the EBS volume is attached and ready for cloud-init to manage. The solution do that is the /usr/local/bin/mount-xvdf script that waits for the attachment of the volume to complete (then formats, configures mount point, then mounts) the EBS volume before starting up the jenkins master docker container.
There is an underlaying issue where …
=> Adding persistent storage

docker/Dockerfile, docker/files/config.xml, docker/files/executors.groovy
Before making any particular customisation, we start committing a "vanilla"
config.xml based on the current status of the Jenkins installation.
At some point, we can become more clever and create a template for it, and
pass values, such as the number of executors, ... However, let's keep it
simple and move fast for now.
Now that we use the config.xml file, we don't need to specify the number
of executors as we were doing, thus I removed the file from Dockerfile.
This has been testing by spinning up a Jenkins on my laptop.
=> Use a static Jenkins configuration file when building the container

docker/files/groovy/configure-github-oauth-jenkins-plugin.groovy, docker/files/plugins.txt, terraform/cloud-init/server-xenial-16.04-amd64-server.yaml, terraform/i-server.tf, terraform/sg-cloudflare.tf, terraform/terraform.tfvars.example, terraform/variables.tf
Enable Github Authentication
- installs github-oauth plugin in to jenkins
- exposes the necessary variables needed to  configure github auth
- installs a configuration script, that if not given secrets will not configure github auth
- enables cloudflare connections inwards (whilst development work on DNS and SSL continues)
- temporarily disable an erroneous output
The github secrets needed for github auth can be passed as a variable when running terraform.
Pair: @smford & @poveyd
=> Enable GitHub Authentication

README.md, terraform/sg-worker.tf
This is very useful for debugging.
I have opened the SSH port only to the subnet, and not to the Internet.
That is clearly for extra security.
That means you will need to use the master node (which is publicly accessible, but IP-restricted)
as a "proxy" in order to SSH into the agents node from your laptop.
I have included documentation that explains how to do that.
=> Add ability to SSH into the agents node

README.md, terraform/ssh-keys.tf, terraform/variables.tf
Rather than computing the path to the public ssh key which is highly opinionated, this change allows a user to specify a public ssh key to use.
Solo: @smford
=> Allow user to specify which SSH public key file to use

docs/README.md, docs/docs_for_re/README.md, docs/docs_for_team/README.md
Add some documentation to wrap up the mission. It is not perfect, it may need a review to improve English and usability. That can be done later on, I feel this is a good start, given the time constraints, resources and other priorities.
In particular it adds:
* documentation for RE on how to deal with a request when the team finished the DNS provisioning
* documentation for the service team on how to use our current MVP to build code.
=> Wrap up documentation

terraform/tools/create-s3-state-bucket, terraform_dns/terraform.tfvars.example, terraform_dns/tools/create-dns-s3-state-bucket
Change bucket creation scripts, and terraform.tfvars_example, to fail fast when invalid characters passed in. These invalid characters are not allowed in S3 bucket names and will prevent AWS creating an S3 bucket.
=> Add bucket name validation on creation

docker/files/groovy/configure-slave-to-master-access.groovy
This enables Agent-to-Master access control, it means access to worker nodes can be selective and removes a security warning.
By being selective it means that varying levels of access control can be granted to the slaves, rather than having the slaves have full control over the jenkins master.
Further documentation is available here: https://wiki.jenkins.io/display/JENKINS/Slave+To+Master+Access+Control
Solo: @smford
=> Restrict Agent-to-Master Access Control

README.md, docs/docs_for_re/README.md
Documentation for Reliability Engineering didn't reflect the complete process, so it wasn't possible to follow.
For example, there were fields missing that had to be filled in.
Also, the URL structure in both RE and end-user docs was wrong, so I had to make most changes in the RE docs, but small changes in the end-user docs too.
May need further editing.
=> Modify documentation for RE

terraform/jenkins/terraform.tfvars.example
We decided that build.gds-reliability.engineering domain can be publicly disclosed.
We changed the README accordingly but we forgot to change this config file
=> Make the RE build domain public

docker/files/groovy/configure-number-of-executors.groovy
Set the number of executors to 0, which prevents jobs running on the master.
Solo: @smford
=> Prevent jobs running on the jenkins master

README.md, terraform/dns/terraform.tfvars.example
Environments are no longer needed now that we no longer use EIPS.
This removes old references to it and updates the documentation.
Solo: @smford
=> Remove concept of environments from dns terraform

README.md
- Fix wrong path for one of the commands to run.
- Remove the reference to a subsection we removed previously.
=> Documentation tweaks 2

README.md, docs/docs_for_re/README.md, terraform/jenkins/terraform.tfvars.example
This has been testing by standing up and environment and it seems to work.
This commit does two things - that is not ideal but they are both simple things:
- move the documentation on how to set up the Github OAuth app from the RE documentation
section to the main installation guide. It also correct the fact that a 'OAuth app' needs
to be created, rather than a 'Github app'.
- the Github OAuth credentials are not stored in the configuration file anymore, but passed
as an argument to Terraform
=> Move Github OAuth docs from RE side to Team side, and avoid storing Github creds in file

docker/files/groovy/add-sample-agent-docker-image.groovy, docs/docs_for_team/README.md
This allows users to copy a template file for loading a docker image to Jenkins. This means that Docker images can be more easily loaded and configured using code rather than through the use of the Jenkins UI. 
The developer docs have been changed to reflect this. 
https://trello.com/c/48vnGYCe/148-test-whether-an-agent-image-can-be-created-by-using-the-build-toolchain-as-a-base
=> Develop worker docker image

docs/docs_for_team/README.md
Whilst tearing down a test environment I noticed that I had to perform a terraform init. Currently the instructions to do this live only in the set up instructions and flipping between these and the docs on decommissioning is annoying. This adds the command for performing a `terraform init` into the relevant places in the teardown procedure.
=> Adjust teardown instructions to include `terraform init`

docs/docs_for_team/README.md
Whilst making changes to the way in which Docker images are loaded we noticed that things were not working in the way we expected. Basically code was being loaded into terraform from the developers local git master branch. This means that old code could be used to initialise Jenkins and changes to the development branch would not. 
There isn't an easy fix to this at the moment so a trello card will be made to address the issue. For the time being teams need to be aware of this so that they can test changes in development environments.
=> Add known bugs section to README

docker/Dockerfile
The issues where:
- use of double quotes around the healthcheck CMD
- nc was not installed on the container
We could have used curl instead of nc for the healthcheck, as it was already
installed on the container. However, @smford suggested we don't use curl
as it has got issues, e.g. if theres a redirect (30x) it doesn't give a
clean/happy error code
=> Fix healthcheck for master Docker container

terraform/jenkins/asg.tf, terraform/jenkins/cloud-init/server-asg-xenial-16.04-amd64-server.yaml, terraform/jenkins/cloud-init/worker-xenial-16.04-amd64-server.yaml, terraform/jenkins/dns.tf, terraform/jenkins/i-worker.tf
The Route 53 records for the internal dns are in the form:
[environment].internal
This causes confusion when multiple teams use the same environment name and the same aws account.  By adding team name to the internal dns zone it removes the confusion, resulting in:
[environment].[team].internal
Solo: @smford
=> Fix confusing internal DNS naming scheme

docker/Dockerfile
This works - more complex expressions fail for some reason.
The default values of interval, timeout, ... should work fine for us.
This has been tested:
- launch container
- see healthy state
- stop nginx within the container
- see unhealthy state
=> Fix docker healthcheck for the master containers

terraform/jenkins/tls.tf
When running a terraform destroy, it will error on the destruction of the TLS cert being in use.
Following the recommendations and documention from a slightly newer version of terraform, they recommend setting create before destroy.
Further details available [here](https://github.com/terraform-providers/terraform-provider-aws/issues/4537) and [here](https://github.com/terraform-providers/terraform-provider-aws/pull/4925/files)
Solo: @smford
=> Fix lifecycle for TLS Cert

docker/files/groovy/add-sample-agent-docker-image.groovy, docs/docs_for_team/README.md
Just make it clearer that that is just a sample image, to run the sample project.
So that teams are reminded to build the image themselves, following their standards.
=> Update name and label of sample Docker container of the Jenkins agent

README.md, terraform/jenkins/asg.tf, terraform/jenkins/sg-asg.tf
This enables ssh'ing to the master using the nice ELB hostname - similar to: jenkins2.my-env.my-team.build.gds-reliability.engineering
Once ssh'd to the master, you can proxy to the workers.
Solo: @smford
=> Enable ssh to master

docs/docs_for_team/README.md
This gives a more detailed description of the process needed to create and run a new docker image for the agents that can be run by Jenkins
=> Improve instruction on building image 2

README.md, examples/complete_deployment_of_dns_and_jenkins/README.md, examples/gds_specific_dns_and_jenkins/README.md
This matches with the PR [here](https://github.com/alphagov/terraform-aws-re-build-jenkins/pull/5)
Solo: @smford
=> Remove jenkins2 aka server_name from url

docker/files/groovy/configure-jenkins-url.groovy
This sets the jenkins url which removes a warning.  It pairs with this [PR](https://github.com/alphagov/terraform-aws-re-build-jenkins/pull/7)
Solo: @smford
=> Set Jenkins url via groovy to remove jenkins warning

docker/files/groovy/configure-disable-usage-stats.groovy
Jenkins sends usage statistics daily to jenkins.io, this disables it doing it.
Solo: @smford
=> Disable sending jenkins usage statistics to jenkins.io

examples/complete_deployment_of_dns_and_jenkins/README.md, examples/complete_deployment_of_dns_and_jenkins/main.tf, examples/complete_deployment_of_dns_and_jenkins/terraform.tfvars.example, examples/complete_deployment_of_dns_and_jenkins/variables.tf, examples/gds_specific_dns_and_jenkins/README.md, examples/gds_specific_dns_and_jenkins/jenkins/main.tf, examples/gds_specific_dns_and_jenkins/jenkins/terraform.tfvars.example, examples/gds_specific_dns_and_jenkins/jenkins/variables.tf
We want to control and pin the jenkins version, this PR updates documentation and examples showing how to change the jenkins_version.
This PR goes with [this PR](https://github.com/alphagov/terraform-aws-re-build-jenkins/pull/8)
Solo: @smford
=> Removing ability to overide jenkins version

examples/complete_deployment_of_dns_and_jenkins/main.tf, examples/gds_specific_dns_and_jenkins/dns/main.tf, examples/gds_specific_dns_and_jenkins/jenkins/main.tf
This sets the examples to use release 0.0.1 of both the jenkins and dns module, and means that a local symlink to the repo is no longer required.
Solo: @smford
=> Update examples to use first module release

examples/complete_deployment_of_dns_and_jenkins/README.md, examples/complete_deployment_of_dns_and_jenkins/main.tf, examples/complete_deployment_of_dns_and_jenkins/terraform.tfvars.example, examples/complete_deployment_of_dns_and_jenkins/variables.tf, examples/gds_specific_dns_and_jenkins/README.md, examples/gds_specific_dns_and_jenkins/jenkins/main.tf, examples/gds_specific_dns_and_jenkins/jenkins/terraform.tfvars.example, examples/gds_specific_dns_and_jenkins/jenkins/variables.tf
This aligns with the upgrade process vision, and prevents legacy versions
being installed.
This pairs with this [PR](https://github.com/alphagov/terraform-aws-re-build-jenkins/pull/10)
Solo: @smford
=> By removing specific docker version it will always install the latest.

examples/complete_deployment_of_dns_and_jenkins/main.tf, examples/gds_specific_dns_and_jenkins/dns/main.tf, examples/gds_specific_dns_and_jenkins/jenkins/main.tf
The examples had the module versions pinned to v0.0.1, this causes maintenance overhead and confusion by the end user.  Instead I have removed module version pinning (to releases) meaning they use the latest (master branch) and have added inline documentation detailing how one may choose to pin if needed.
Solo: @smford
=> Remove module version pinning from examples

docs/docs_for_team/README.md
During some user research it was brought up that some of the instructions around publishing and linking of docker images were not as clear as they should be. This goes some way to fixing that
=> Improve readibility and flow of re team README

docs/docs_for_team/README.md, examples/complete_deployment_of_dns_and_jenkins/files/custom-script.groovy, examples/gds_specific_dns_and_jenkins/jenkins/files/custom-script.groovy
The restart was causing Jenkins to go into a restart loop. This removes the restart and adds a step to the docs for team to reflect the fact that they need to restart manually
Related to:
https://github.com/alphagov/terraform-aws-re-build-jenkins/pull/28
=> Remove a restart from the custom groovy script

examples/complete_deployment_of_dns_and_jenkins/README.md, examples/gds_specific_dns_and_jenkins/README.md
Solo: @poveyd
Previously, it was optional whether Github OAuth is used to secure Jenkins. This has now changed. Github OAuth is now required when setting up Jenkins. This change just updates the documentation in the examples.
=> Change example docs to record github OAuth parameters as being required

docs/README.md, docs/shared-responsibility-document.md
Trello card: https://trello.com/c/JOX169Wr/198-create-security-shared-responsibility-documentation
This shared responsibility document has gone through tech writer review.
The document is modelled on Amazon's AWS shared responsibility document and explains the division of responsibility between GDS' RE team, the user of this build system, and third parties.
=> Add shared responsiblity document
