alphagov/re-build-systems

- terraform/ssh-keys.tf
Just changed the directory path to config
> Change config path

- README.md
Just added the README.txt from the re-ci-mission repo. Have added a couple of extra sentences which may help new users.
> Copied README.txt from re-ci-mission

- terraform/ssh-keys.tf
Just changed the path from configuration to config.
> Change path

- .pre-commit-config.yaml
Adding git pre-commit config file
> Adding git pre-commit config file

- LICENCE
- README.md
The GDS way licensing guidelines have been followed
https://gds-way.cloudapps.digital/manuals/licensing.html#licensing
> Add licence

- README.md
Improvements to the README file
> Documentation improvements 2

- README.md
These are just a couple - this PR is just the beginning, to have a place to add more as we think of them.
> Add recommandations to README.md

- CONTRIBUTING.md
- README.md
General improvements of the documentation
> Documentation improvement

- docs/architecture/README.md
- docs/architecture/decisions/0001-record-architecture-decisions.md
This is similar to what GOV.UK is doing but a bit more lightweight, without the use of special tooling, a bit similar to what Pay is doing
> Start tracking ADRs

- docker/files/plugins.txt
Install the plugin needed to orchestrate docker
Solo: @smford
> Enable Docker-plugin

- docker/Dockerfile
- docker/files/groovy/configure-csrf-protection.groovy
- docker/files/groovy/configure-docker-plugin.groovy
- docker/files/groovy/configure-jnlp-agent-protocols.groovy
- docker/files/groovy/configure-worker-port.groovy
- terraform/cloud-init/master-xenial-16.04-amd64-server.yaml
- terraform/instances.tf
Configure parts of jenkins using groovy scripts and enable internal dns resolution against the <environment>.internal
> Configure Jenkins

- terraform/dns.tf
Creates internal and external dns zone
Solo: @smford
> Enable Internal and External DNS

- docker/jobs/Hello-World/config.xml
Simple Hello World job that demonstrates running on docker workers.
Solo: @smford
> Updating Hello-World job for Docker

- terraform/outputs.tf
> Fix naming issue with renamed SGs in output

- docker/jobs/Hello-World/config.xml
The docker worker has the label "docker-jnlp" not "docker-worker-1"
Pair: @poveyd & @smford
> Assign Hello-World job to correct docker worker

- terraform_dns/main.tf
> Add helpful instructions for users

- docs/architecture/decisions/0002-use-containers-and-multiple-boxes.md
Document the original decisions around architecture.
I wasn't around for these so I may not have got the reasons right - feel free to correct me.
> Add architecture ADR.

- README.md
- terraform/jenkins/terraform.tfvars.example
A number of commits to change the documentation, as agreed and articulated in the 'Actions following research analysis session' Google doc. 
Some changes are to ensure consistent approach/style. Some are to make it easier for users to follow the documentation.
One change is to the example Terraform config file. This change is to make it clearer to the user which settings they should change and which they should not.
> Update readme + a little bit of terraform

- README.md
Documentation update of the DNS section to reflect the conventions
set in the Jenkins section regarding how to explain in what directory
commands should be run.
> Update README (DNS section)

- terraform/jenkins/outputs.tf
> Adding github callback url to output

- docs/docs_for_team/README.md
Add documentation on uninstalling the platform.
> Add documentation on uninstalling the platform

- docs/docs_for_team/README.md
https://github.com/alphagov/re-build-systems/pull/87
The above pr introduced a small typo which this fixes
> Small typo fix

- .gitignore
- terraform/dns/.gitignore
- terraform/jenkins/.gitignore
> Exclude some Terraform files

- examples/gds_specific_dns_and_jenkins/README.md
- examples/gds_specific_dns_and_jenkins/dns/.gitignore
- examples/gds_specific_dns_and_jenkins/dns/main.tf
- examples/gds_specific_dns_and_jenkins/dns/outputs.tf
- examples/gds_specific_dns_and_jenkins/dns/provider.tf
- examples/gds_specific_dns_and_jenkins/dns/terraform.tfvars.example
- examples/gds_specific_dns_and_jenkins/dns/variables.tf
- examples/gds_specific_dns_and_jenkins/jenkins/.gitignore
- examples/gds_specific_dns_and_jenkins/jenkins/dns-remote-state.tf
- examples/gds_specific_dns_and_jenkins/jenkins/main.tf
- examples/gds_specific_dns_and_jenkins/jenkins/outputs.tf
- examples/gds_specific_dns_and_jenkins/jenkins/provider.tf
- examples/gds_specific_dns_and_jenkins/jenkins/terraform.tfvars.example
- examples/gds_specific_dns_and_jenkins/jenkins/variables.tf
- terraform example of how to use new modules to deploy dns and jenkins within gds environment
- documentation to support example
Solo: @smford
> Adding gds specific example

- tools/generate-plugin-list
Script to generate list of plugins and versions, usedfor generating docker/files/plugins.txt file.
Solo: @smford
> Script to generate plugin and dependancy list file

- examples/complete_deployment_of_dns_and_jenkins/README.md
- examples/complete_deployment_of_dns_and_jenkins/main.tf
- examples/complete_deployment_of_dns_and_jenkins/terraform.tfvars.example
- examples/complete_deployment_of_dns_and_jenkins/variables.tf
- examples/gds_specific_dns_and_jenkins/jenkins/main.tf
- examples/gds_specific_dns_and_jenkins/jenkins/variables.tf
The ubuntu version has been pinned to xenial. Removing ability to override.
Solo: @smford
> Remove ability for users to overide ubuntu version

- examples/complete_deployment_of_dns_and_jenkins/main.tf
- examples/gds_specific_dns_and_jenkins/jenkins/main.tf
- examples/gds_specific_dns_and_jenkins/jenkins/terraform.tfvars.example
> Remove ubuntu_version variable from examples

- README.md
- docs/README.md
- examples/complete_deployment_of_dns_and_jenkins/README.md
- examples/gds_specific_dns_and_jenkins/README.md
PT-G did a tech review on a new branch. Major changes were then made to
the code base due to modularisation. This PR takes into consideration
their content changes (i.e. style and content) and also the changes to
documentation based on the modularisation.
> Merge changes to documentation after tech writer review

- examples/complete_deployment_of_dns_and_jenkins/README.md
- examples/gds_specific_dns_and_jenkins/README.md
Minor changes:
- fixed whitespace to ensure comments matched step
- fixed whitespace to make step numbering work
- converted all links to use same format
- fixed links issue (needed a newline before)
- added Prerequisites to complete example documentation
Solo: @smford
> Example doc tweaking

- docs/architecture/decisions/0005-cloud-init-to-use-script-method
> ADR for converting cloud-init config from yaml to script

- examples/gds_specific_dns_and_jenkins/jenkins/files/custom-script.groovy
- examples/gds_specific_dns_and_jenkins/jenkins/terraform.tfvars.example
The location and filename has changed during development of this function.
This change updates the tfvars example to match the actual location and name of the file.
> Updating example script name and location

- examples/complete_deployment_of_dns_and_jenkins/README.md
- examples/complete_deployment_of_dns_and_jenkins/main.tf
- examples/complete_deployment_of_dns_and_jenkins/variables.tf
- examples/create_dns_jenkins_s3_using_scripts/jenkins/main.tf
- examples/create_dns_jenkins_s3_using_scripts/jenkins/variables.tf
- examples/gds_specific_dns_and_jenkins/README.md
- examples/gds_specific_dns_and_jenkins/jenkins/main.tf
- examples/gds_specific_dns_and_jenkins/jenkins/variables.tf
Trello card #212
- Replaced variable names to make them more readable and have correct meaning.
- Also see Jenkins module repo for connected changes.
- Tested using "terraform plan"
> Replaced github admin user with jenkins admin where referenced in vars

- docs/architecture/decisions/0006-buildah-discovery.md
> Adding buildah discovery ADR

- examples/complete_deployment_of_dns_and_jenkins/terraform.tfvars.example
- examples/gds_specific_dns_and_jenkins/jenkins/terraform.tfvars.example
Missed this variable rename in 2 example files.
> Quick edit to rename example jenkins admin usernames

- docs/docs_for_team/README.md
- examples/complete_deployment_of_dns_and_jenkins/files/custom-script.groovy
- examples/gds_specific_dns_and_jenkins/jenkins/files/custom-script.groovy
This allows the user to add jobs in a slightly simpler way and should cut down on the size of this file slightly for teams with many jobs
> Add an iterable list of job definitions

- docs/docs_for_team/README.md
Related to https://github.com/alphagov/terraform-aws-re-build-jenkins/pull/25
> Edit docs to use custom groovy script when adding docker images

- docs/docs_for_team/README.md
- examples/gds_specific_dns_and_jenkins/jenkins/files/custom-script.groovy
The goal is to make it easier for the user to customise the Jenkins configuration.
We have made the minimum changes in the documentation, as we are going to review it as a whole soon.
@with JonathanHallam
> Refactor the custom Groovy script code

- examples/complete_deployment_of_dns_and_jenkins/files/custom-script.groovy
In PR https://github.com/alphagov/re-build-systems/pull/142 we forgot to update
both the custom groovy scripts in the two examples. This remediates.
> Update sample custom groovy script

- docs/docs_for_team/README.md
- examples/complete_deployment_of_dns_and_jenkins/files/custom-script.groovy
- examples/gds_specific_dns_and_jenkins/jenkins/files/custom-script.groovy
This includes both the job and the agent image to run it.
This relates to this PR https://github.com/alphagov/terraform-aws-re-build-jenkins/pull/26
with @JonathanHallam
> Move sample job to examples

- docs/docs_for_team/README.md
Explain how to customise cloud-init and reprovision the platform.
> Add to the documentation for the team

- docs/docs_for_team/README.md
Be clearer on the steps involved and why it is needed to delete the content of EFS
> Improve re-provisioning doc

- docs/docs_for_re/README.md
minor change to make link clearer
> Update link for accessibility

- docs/docs_for_re/upgrading_versions.md
- examples/complete_deployment_of_dns_and_jenkins/README.md
- examples/complete_deployment_of_dns_and_jenkins/provider.tf
- examples/gds_specific_dns_and_jenkins/README.md
- examples/gds_specific_dns_and_jenkins/dns/provider.tf
- examples/gds_specific_dns_and_jenkins/jenkins/provider.tf
- Add documentation on how to prepare a new release of Jenkins
- updated required version of Terraform
- updated version of the AWS provider
with @daniele-occhipinti 
Link to ticket: https://trello.com/c/fDsVbzzt/240-cut-a-release-september-2018
> Version upgrade

- examples/complete_deployment_of_dns_and_jenkins/main.tf
- examples/gds_specific_dns_and_jenkins/jenkins/main.tf
> Minor fix to formatting
